package cn.com.transcosmos.training.mapper;

import cn.com.transcosmos.training.domain.Project;
import cn.com.transcosmos.training.domain.ProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @SelectProvider(type=ProjectSqlProvider.class, method="countByExample")
    long countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @DeleteProvider(type=ProjectSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @Delete({
        "delete from tbl_project",
        "where pro_id = #{proId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @Insert({
        "insert into tbl_project (pro_id, pro_name, ",
        "dept_id, del_flag)",
        "values (#{proId,jdbcType=VARCHAR}, #{proName,jdbcType=VARCHAR}, ",
        "#{deptId,jdbcType=INTEGER}, #{delFlag,jdbcType=CHAR})"
    })
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @InsertProvider(type=ProjectSqlProvider.class, method="insertSelective")
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @SelectProvider(type=ProjectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="pro_id", property="proId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="pro_name", property="proName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.INTEGER),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.CHAR)
    })
    List<Project> selectByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @Select({
        "select",
        "pro_id, pro_name, dept_id, del_flag",
        "from tbl_project",
        "where pro_id = #{proId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="pro_id", property="proId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="pro_name", property="proName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.INTEGER),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.CHAR)
    })
    Project selectByPrimaryKey(String proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_project
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    @Update({
        "update tbl_project",
        "set pro_name = #{proName,jdbcType=VARCHAR},",
          "dept_id = #{deptId,jdbcType=INTEGER},",
          "del_flag = #{delFlag,jdbcType=CHAR}",
        "where pro_id = #{proId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Project record);
}