package cn.com.transcosmos.training.domain;


public class Condition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.select_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private Integer selectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.select_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String selectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.user_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.period
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.start_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.end_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.person_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.use_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String useDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_select.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.select_id
     *
     * @return the value of tbl_select.select_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public Integer getSelectId() {
        return selectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.select_id
     *
     * @param selectId the value for tbl_select.select_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setSelectId(Integer selectId) {
        this.selectId = selectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.select_name
     *
     * @return the value of tbl_select.select_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getSelectName() {
        return selectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.select_name
     *
     * @param selectName the value for tbl_select.select_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setSelectName(String selectName) {
        this.selectName = selectName == null ? null : selectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.user_id
     *
     * @return the value of tbl_select.user_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.user_id
     *
     * @param userId the value for tbl_select.user_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.period
     *
     * @return the value of tbl_select.period
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.period
     *
     * @param period the value for tbl_select.period
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.start_date
     *
     * @return the value of tbl_select.start_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.start_date
     *
     * @param startDate the value for tbl_select.start_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.end_date
     *
     * @return the value of tbl_select.end_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.end_date
     *
     * @param endDate the value for tbl_select.end_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.dept_id
     *
     * @return the value of tbl_select.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.dept_id
     *
     * @param deptId the value for tbl_select.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.pro_id
     *
     * @return the value of tbl_select.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.pro_id
     *
     * @param proId the value for tbl_select.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.person_name
     *
     * @return the value of tbl_select.person_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.person_name
     *
     * @param personName the value for tbl_select.person_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.use_date
     *
     * @return the value of tbl_select.use_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.use_date
     *
     * @param useDate the value for tbl_select.use_date
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setUseDate(String useDate) {
        this.useDate = useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_select.del_flag
     *
     * @return the value of tbl_select.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_select.del_flag
     *
     * @param delFlag the value for tbl_select.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}