package cn.com.transcosmos.training.domain;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_project.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_project.pro_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_project.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_project.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_project.pro_id
     *
     * @return the value of tbl_project.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_project.pro_id
     *
     * @param proId the value for tbl_project.pro_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_project.pro_name
     *
     * @return the value of tbl_project.pro_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_project.pro_name
     *
     * @param proName the value for tbl_project.pro_name
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_project.dept_id
     *
     * @return the value of tbl_project.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_project.dept_id
     *
     * @param deptId the value for tbl_project.dept_id
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_project.del_flag
     *
     * @return the value of tbl_project.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_project.del_flag
     *
     * @param delFlag the value for tbl_project.del_flag
     *
     * @mbg.generated Mon Feb 26 11:42:18 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}